const {
    DOWNLOAD_PHOTO_PATH,
    DOWNLOAD_VIDEO_PATH,
    REDIS_PORT,
    REDIS_HOST
} = require('../../env')
const path = require('path')

const PREFIX = 'SIWI_DOWNLOAD'
module.exports = {
    SERVICE_NAME: `${PREFIX}`,
    WAIT_DURATION_60: 60,
    WAIT_DURATION_300: 300,
    WAIT_DURATION_600: 600,
    COMMON_WAIT_DURATION: 5,
    DOWNLOAD_VIDEO_LIST: `${PREFIX}:DOWNLOAD_VIDEO_LIST`, // 视频任务列表
    DOWNLOAD_PHOTO_LIST: `${PREFIX}:DOWNLOAD_PHOTO_LIST`, // 图片任务列表
    CURRENT_PHOTO_TASKING: `${PREFIX}:CURRENT_PHOTO_TASKING`,
    CURRENT_VIDEO_TASKING: `${PREFIX}:CURRENT_VIDEO_TASKING`,
    DOWNLOAD_PHOTO_PATH: DOWNLOAD_PHOTO_PATH ? DOWNLOAD_PHOTO_PATH : path.resolve('./storage'),
    DOWNLOAD_VIDEO_PATH: DOWNLOAD_VIDEO_PATH ? DOWNLOAD_VIDEO_PATH : path.resolve('./storage'),
    DOWNLOAD_SUCCESS_LIST: `${PREFIX}:DOWNLOAD_SUCCESS_LIST`,
    DOWNLOAD_FAIL_LIST: `${PREFIX}:DOWNLOAD_FAIL_LIST`,
    DOWNLOAD_PHOTO_WAIT_TIMES: `${PREFIX}:DOWNLOAD_PHOTO_WAIT_TIMES`,
    DOWNLOAD_VIDEO_WAIT_TIMES: `${PREFIX}:DOWNLOAD_PHOTO_WAIT_TIMES`,
    MONITOR_SET_VIDEO_WAIT_DURATION: `${PREFIX}:MONITOR_SET_VIDEO_WAIT_DURATION`,
    MONITOR_SET_PHOTO_WAIT_DURATION: `${PREFIX}:MONITOR_SET_PHOTO_WAIT_DURATION`, //监控设置
    LOGGER_LIST: `${PREFIX}:LOGGER_LIST`, //日志队列,
    SERVICE_ALIVE_REPORT: `${PREFIX}:SERVICE_ALIVE_REPORT`, // 存活上报
    ALIVE_REPORT_DURATION: 300, // 存活上报
    REDIS_PORT: REDIS_PORT,
    REDIS_HOST: REDIS_HOST,
}